<a href="https://colab.research.google.com/github/rezwanh001/Advanced-Programming-Java/blob/master/Linear_Regression_with_one_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Check the GPU 

In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


### Mount the gdrive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


## Model and Cost Function:
----------------------------------------------
      
  * `m` = Number of training examples.

  *  `X's` = Input variable/Features.

  * ` y's `= Outout variable/Target variable.

  * `(X,y)` = one training example.

  * ($X^{(i)}, y^{(i)}$) = $i$-th training example.
  
  
  
So here's how this supervised learning algorithm works. To describe the supervised learning problem slightly more formally, our goal is, given a training set, to learn a function `h : X → y` so that `h(x)` is a “good” predictor for the corresponding value of `y`. For historical reasons, this function `h` is called a hypothesis. Seen pictorially, the process is therefore like this:
  
   ![hypo](https://user-images.githubusercontent.com/15044221/52900513-ed1db480-3220-11e9-9b11-a0f96a5a7854.png)

    Fig-1: The Process the supervised learning algorithms.
   
 When the target variable that we’re trying to predict is continuous, such as in our housing example, we call the learning problem a regression problem. When `y` can take on only a small number of discrete values (such as if, given the living area, we wanted to predict if a dwelling is a house or an apartment, say), we call it a classification problem.
 
   * ***How do we represent `h`?***
        
        $h_\theta(X)$ = $\theta_0 + \theta_1(X)$        --------------------------------------------------------------------------(i)
        
  
  
  *  ***How to fit the best possible straight line in our data?***
     
    * Hypothesis: $h_\theta(x)$ = $\theta_0 + \theta_1x$  -----------------------------------------------------------(ii)
    
    * $\theta_{i}$'s  = Parameters.
    
    * Idea: Choose $\theta_0$, $\theta_1$ so that $h_\theta(x)$ is close to $y$ for our training examples$(X, y)$
    
    * Let's formalize this. So linear regression, what we're going to do is, I'm going to want to solve a minimization problem. So I'll write minimize over $\theta_0$, $\theta_1$ with following formula:
    
         $\underset{\theta_0, \theta_1}{minimize}$ =$\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(X^{(i)}) - y^{(i)})^2$      -------------------------------(iii)
    
    
   * ***Cost function:***
   
      *  $J(\theta_0, \theta_1)$ = $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(X^{(i)}) - y^{(i)})^2$      -------------------------------------------(iv)
     
     This cost function is also known as Squared Error Function.
     
      It turns out that why do we take the squares of the errors. It turns out that these squared error cost function is a reasonable choice and works well for problems for most regression programs. There are other cost functions that will work pretty well. But the square cost function is probably the most commonly used one for regression problems.
      
      We can measure the accuracy of our hypothesis function by using a **cost function**. This takes an average difference (actually a fancier version of an average) of all the results of the hypothesis with inputs from $x$'s and the actual output $y$'s.
      
      * $J(\theta_0, \theta_1)$ =  $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(\hat{y_i} - y_i)^2$  = $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(X^{(i)}) - y^{(i)})^2$      ----------(v)
      
   To break it apart, it is $\frac{1}{2}\bar{x}$ where $\bar{x}$ is the mean of the squares of $h_\theta (x_{i}) - y_{i}$ or the difference between the predicted value and the actual value.
      
      This function is otherwise called the "Squared error function", or "Mean squared error". The mean is halved $\left(\frac{1}{2}\right)$ as a convenience for the computation of the gradient descent, as the derivative term of the square function will cancel out the $\frac{1}{2}$ term.

    
* ***What the cost function is doing, and why we want to use it?***
 
 * Hypothesis: 
 
    $h_\theta(x)$ = $\theta_0 + \theta_1x$
 
 * Parameters:
 
    $\theta_0$, $\theta_1$
 
 * Cost Function:
    
    $J(\theta_0, \theta_1)$ = $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(X^{(i)}) - y^{(i)})^2$ 
    
 * Goal: 
   
   $\underset{\theta_0, \theta_1}{minimize}$ $J(\theta_0, \theta_1)$

     ![cost_func](https://user-images.githubusercontent.com/15044221/52915185-f5e2b900-32fa-11e9-8b57-c86b272675f1.png)

       Fig-2: Plot the Hypothesis Function where $\theta_0$=$0$, $x$ is the size of house.
       
      ![cost_funct](https://user-images.githubusercontent.com/15044221/52915671-1f064800-3301-11e9-8502-6b622456ba7e.png)
      
      Fig-3: Plot the Cost Function where $\theta_0$=$0$, $\theta_1$=$1$.
      
       
 * **Simplified**
 
  * Hypothesis: 
 
    $h_\theta(x)$ = $\theta_1x$
 
  * Parameters:
 
    $\theta_1$
 
  * Cost Function:
    
    $J(\theta_1)$ = $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(X^{(i)}) - y^{(i)})^2$ 
    
  * Goal: 
   
    $\underset{\theta_1}{minimize}$ $J(\theta_1)$

   *Two key functions we want to understand:*
   
   1. $h_\theta(x)$ : For fixed $\theta_1$, this is a function of $x$. So the hypothsis is a finction of, what is the size of the house $x$.
   2. $J(\theta_1)$: Function of the parameter $\theta_1$. In contrast, $J$, that's a function of parameter, $\theta_1$, which controls the slope of the straight line.
    
   
   If we try to think of it in visual terms, our training data set is scattered on the x-y plane. We are trying to make a straight line (defined by $h_\theta(x)$) which passes through these scattered data points.

Our objective is to get the best possible line. The best possible line will be such so that the average squared vertical distances of the scattered points from the line will be the least. Ideally, the line should pass through all the points of our training data set. 

Thus as a goal, we should try to minimize the cost function. In this case, $\theta_1$ = $1$ is our global minimum.
   

## Parameter Learning
-------------------------------------

### Gradient Descent: 

   * Gradient descent is an algorithm for minimizing the cost function $J$. It turns out gradient descent is a more general algorithm, and is used not only in linear regression. It's actually used all over the place in machine learning.
   
   * Have some function, $J(\theta_0, \theta_1)$ 
   * Want,  $\underset{\theta_0, \theta_1}{min}$ $J(\theta_0, \theta_1)$ 
   * Outline:
     
      * Start with some $\theta_0$, $\theta_1$
      * Keep changing $\theta_0$, $\theta_1$ to reduce  $J(\theta_0, \theta_1)$  until we hopefully end up at a minimum.
      
   * **Gradient descent algorithm**
   
     * repeat until convergence {
          
          $\theta_j$   := $\theta_j$ - $\alpha$$\frac{\delta}{\delta\theta_j}$ $J(\theta_0, \theta_1)$
          (for $j$=$0$ and $j$=$1$)
          
        }
        
        Where, $\alpha$ = $learning$ $rate$. 
        And what $\alpha$ does is it basically controls how big a step we take downhill with creating descent. So if $\alpha$ is very large, then that corresponds to a very aggressive gradient descent procedure where we're trying take huge steps downhill and if $\alpha$ is very small, then we're taking little, little baby steps downhill.
        
       * If $\alpha$ is too small, gradient descent can be slow.
       * If $\alpha$ is too large, gradient descent can overshoot the minimum. It may fail to converge, or even diverge.

     * What if your parameter $\theta_1$ is already at a local minimum, what do you think one step of gradient descent will do?
      
       * **Ans:** Slope will be equal to $0$. So, Leave $\theta_1$ unchanged. So if your parameters are already at a local minimum one step with gradient descent does not absolutely nothing it doesn't your parameter, which is what you want beacause it keeps your solution at the local optimum.
       
     * Why gradient descent can converse the local minimum even with the learning rate alpha fixed?
      
       * **Ans:** Gradient descent can converge to a local minimum, even with the learning rate $\alpha$ fixed.
      
          $\theta_1$   := $\theta_1$ - $\alpha$$\frac{\delta}{\delta\theta_1}$ $J(\theta_1)$
          
          As we approach a local minimum, gradient descent will automatically take smaller steps. So, on need to decrese $\alpha$ over time.
          
          So that's the gradient descent algorithm and you can use it to try to minimize any cost function $J$, not the cost function $J$ that we defiend for linear regression.
          
     


## Gradient descent for linear regression
-------------------------------------------------------------------

### Linear Regression Model:

* **Hypothesis Function:**  $h_\theta(x) = \theta_0 + \theta_1x$

* ** Squared Error Cost Function: ** $J(\theta_0, \theta_1)$ = $\frac{1}{2m}$ $\sum_{i=1}^{m}$ $(h_\theta(x^{(i)}) - y^{(i)})^2$

     Apply gradient descent to minimize our squared error cost function.
     
     The key term we need is cost function $J$ derivative term over here. So, we need to figure out what is this partial deivative term.
     
     $\frac{\delta}{\delta\theta_j} J(\theta_0, \theta_1) = \frac{\delta}{\delta\theta_j} \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2$
     
     $\frac{\delta}{\delta\theta_j} J(\theta_0, \theta_1) = \frac{\delta}{\delta\theta_j} \frac{1}{2m} \sum_{i=1}^{m} ((\theta_0 + \theta_1x^{(i)}) - y^{(i)})^2$
     
  Partial derivative with respect to $\theta_0$ and $\theta_1$.
     
    *  $\theta_0, J=0: \frac{\delta}{\delta\theta_0} J(\theta_0, \theta_1) =  \frac{1}{m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})$
    
    *  $\theta_1, J=1: \frac{\delta}{\delta\theta_1} J(\theta_0, \theta_1) =  \frac{1}{m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)}).x^{(i)}$
    
 
* ***Gradient descent algorithm for linear regression:***

    * repeat until convergence {
    
    $\theta_0 := \theta_0 - \alpha \frac{\delta}{\delta\theta_j} \frac{1}{m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})$
    
    $\theta_1 := \theta_1 - \alpha \frac{\delta}{\delta\theta_j} \frac{1}{m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)}).x^{(i)}$
    
    }
    
 
 * ** "Batch" Gradient Descent:**
     
     "Batch" : Each step of gradient descent uses all the training examples.
     
     


## Linear Algebra Review
------------------------------------------

* **Matrices and Vectors**
   
   * **Matrix:** Rectangular array of Numbers.
   * **Dimension of Matrix:** Number of rows $x$ numbers of columns.
   * **Vector:** An $nx1$ matrix. Also called $n$-D vector. Also denoted by $\mathbb{R^n}$.
   
   * **Notation and terms:**

      * $A_{ij}$refers to the element in the $i$-th row and $j$-th column of matrix $A$.

      * $A$ vector with $'n'$ rows is referred to as an $'n'$-dimensional vector.

     *  $v_i$  refers to the element in the $i$-th row of the vector.
     
     * In general, all our vectors and matrices will be $1$-indexed. Note that for some programming languages, the arrays are $0$-indexed.
     
     * Matrices are usually denoted by uppercase names while vectors are lowercase.

     * "Scalar" means that an object is a single value, not a vector or matrix.

     * $\mathbb{R}$ refers to the set of scalar real numbers.

     * $\mathbb{R^n}$ refers to the set of $n$-dimensional vectors of real numbers.

   
* **Addition and scalar multiplication**

  * Addition and subtraction are element-wise, so you simply add or subtract each corresponding element:
  
      $\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} + \begin{bmatrix} w & x \newline y & z \newline \end{bmatrix} =\begin{bmatrix} a+w & b+x \newline c+y & d+z \newline \end{bmatrix}$
      
  * In scalar division, we simply divide every element by the scalar value:

      $\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} / x =\begin{bmatrix} a /x & b/x \newline c /x & d /x \newline \end{bmatrix}$
      

* ** Matrix-Vector multiplication **

  * $Prediction = DataMetrix  * Parameters$
  
  * We map the column of the vector onto each row of the matrix, multiplying each element and summing the result.
     
     $\begin{bmatrix} a & b \newline c & d \newline e & f \end{bmatrix} *\begin{bmatrix} x \newline y \newline \end{bmatrix} =\begin{bmatrix} a*x + b*y \newline c*x + d*y \newline e*x + f*y\end{bmatrix}$
     
     The result is a vector. The number of columns of the matrix must equal the number of rows of the vector.

    An m x n matrix multiplied by an n x 1 vector results in an m x 1 vector.
    
    
 * **Matrix-Matrix Multiplication**
    
    * We multiply two matrices by breaking it into several vector multiplications and concatenating the result
    
    $\begin{bmatrix} a & b \newline c & d \newline e & f \end{bmatrix} *\begin{bmatrix} w & x \newline y & z \newline \end{bmatrix} =\begin{bmatrix} a*w + b*y & a*x + b*z \newline c*w + d*y & c*x + d*z \newline e*w + f*y & e*x + f*z\end{bmatrix}$
    
    An m x n matrix multiplied by an n x o matrix results in an m x o matrix. In the above example, a 3 x 2 matrix times a 2 x 2 matrix resulted in a 3 x 2 matrix.

    To multiply two matrices, the number of columns of the first matrix must equal the number of rows of the second matrix.
    
    
 * ** Matrix Multiplication Properties**
 
    * Matrices are not commutative: $A∗B \neq B∗A$
    * Matrices are associative: $(A∗B)∗C =  A∗(B∗C)$
    * The identity matrix, when multiplied by any matrix of the same dimensions, results in the original matrix. It's just like multiplying numbers by 1. The identity matrix simply has 1's on the diagonal (upper left to lower right diagonal) and 0's elsewhere.
    
    $\begin{bmatrix} 1 & 0 & 0 \newline 0 & 1 & 0 \newline 0 & 0 & 1 \newline \end{bmatrix}$

   * When multiplying the identity matrix after some matrix (A∗I), the square identity matrix's dimension should match the other matrix's columns. When multiplying the identity matrix before some other matrix (I∗A), the square identity matrix's dimension should match the other matrix's rows. 
   
   
 * **Inverse and Transpose**
 
   * Matrices that don't have inverse are "singular" or "degenerate".
   * Let $A$ be an $(mxn)$ matrix, and let $B = A^T$. Then $B$ is an $(nxm)$ matrix, and $B_{ij} = A_{ji}$
   * The inverse of a matrix $A$ is denoted $A^{-1}$. Multiplying by the inverse results in the identity matrix.
   * A non square matrix does not have an inverse matrix. We can compute inverses of matrices in octave with the $pinv(A)$ function and in Matlab with the $inv(A)$  function. Matrices that don't have an inverse are *singular* or *degenerate*.
   * The transposition of a matrix is like rotating the matrix $90°$ in clockwise direction and then reversing it. We can compute transposition of matrices in matlab with the $transpose(A)$ function or $A'$:
   
       $A = \begin{bmatrix} a & b \newline c & d \newline e & f \end{bmatrix}$
   
       $A^T = \begin{bmatrix} a & c & e \newline b & d & f \newline \end{bmatrix}$
       
   * In other words: $A_{ij} = A^{T}_{ji}$
   

## Linear Algebra Review: Python Code 

In [3]:
## Matrix and Vector
##-------------------

### Initialize matrix A with 4 rows and 3 cols
# Load library
import numpy as np
A = np.matrix([[1,2,3], [4,5,6], [7,8, 9],[10,11,12]])
print("Matrix: \n", A)

### Initialize a vector
v = np.matrix([1,2,3])
print("Vector: ", v)


### Get the dimension of the matrix A where m = rows and n = cols
[m, n] = A.shape
print("Dim A: ", [m, n])

###You could also store it this way
dim_A = A.shape
print("dim_A: ", dim_A)

### Get the dimension of the vector v
dim_v = v.shape
print("dim_v: ", dim_v)

### Now let's index into the 2nd row and 3rth cols of matrix A.
A_23 = A.item(2-1, 3-1)
print("A_23: ", A_23)



Matrix: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vector:  [[1 2 3]]
Dim A:  [4, 3]
dim_A:  (4, 3)
dim_v:  (1, 3)
A_23:  6


In [4]:
## %%%%%%%%% Addition and Scalar Multiplication %%%%%%%%%%%%
## %--------------------------------------------------

## % Initialize matrix A and B
A = np.matrix([[1,2,4], [5,3,2]])
B = np.matrix([[1,3,4], [1,1,1]])
print("Matrix A: \n", A)
print("Matrix B: \n", B)
## % Initialize constant s
s = 2

## % See how the element-wise addition works.
add_AB = A + B
print("add_AB: \n", add_AB)

## % See how the element-wise subtraction works.
sub_AB = A - B
print("sub_AB: \n", sub_AB)

## % Divide A by s
div_As = A / s
print("div_As: \n", div_As)

## % What happens if we have a Matrix  + scalar?
add_As = A + s
print("add_As: \n", add_As)


Matrix A: 
 [[1 2 4]
 [5 3 2]]
Matrix B: 
 [[1 3 4]
 [1 1 1]]
add_AB: 
 [[2 5 8]
 [6 4 3]]
sub_AB: 
 [[ 0 -1  0]
 [ 4  2  1]]
div_As: 
 [[0.5 1.  2. ]
 [2.5 1.5 1. ]]
add_As: 
 [[3 4 6]
 [7 5 4]]


In [5]:
### %%%%% Matrix Vector Multiplication
## %%%-------------------------------
### % Initialize a 3 by 2 matrix 
A = np.matrix([[1, 2], [3, 4],[5, 6]])
print("Matrix A: \n", A)

### % Initialize a 2 by 1 matrix 
B = np.matrix([1, 2])
print("Matrix: \n", B)

### % Multiply A * B
mult_AB = A.dot(B.T)
print("mult_AB: \n", mult_AB)


Matrix A: 
 [[1 2]
 [3 4]
 [5 6]]
Matrix: 
 [[1 2]]
mult_AB: 
 [[ 5]
 [11]
 [17]]


In [6]:
### %%%% Matrix Multiplication Properties
## %%------------------------------------
## % Initialize random matrices A and B 
A = np.matrix([[1,2],[4,5]])
B = np.matrix([[1,1],[0,2]])
print("Matrix A: \n", A)
print("Matrix B: \n", B)

## % Initialize a 2 by 2 identity matrix
I = np.identity(2)
print("Identity Matrix: \n", I)

### % The above notation is the same as I = [1,0;0,1]

## % What happens when we multiply I*A ? 
IA = I.dot(A)
print("I*A: \n", IA)

## % How about A*I ? 
AI = A.dot(I)
print("A*I: \n", AI)

## % Compute A*B 
AB = np.dot(A, B)
print("A*B: \n", AB)

## % Is it equal to B*A? 
BA = np.dot(B, A)
print("B*A: \n", BA)

### % Note that IA = AI but AB != BA


Matrix A: 
 [[1 2]
 [4 5]]
Matrix B: 
 [[1 1]
 [0 2]]
Identity Matrix: 
 [[1. 0.]
 [0. 1.]]
I*A: 
 [[1. 2.]
 [4. 5.]]
A*I: 
 [[1. 2.]
 [4. 5.]]
A*B: 
 [[ 1  5]
 [ 4 14]]
B*A: 
 [[ 5  7]
 [ 8 10]]


In [7]:
### %%%%% Inverse and Transpose
### %%-------------------------

## % Initialize matrix A
A = np.matrix([[1,2,0], [0,5,6], [7,0,9]])
print("Matrix A: \n", A)

## % Transpose A
A_trans = A.T
print("Matrix A_trans: \n", A_trans)

## % Take the inverse of A
A_inv = A.I
print("A_inv: \n", A_inv)

## % What is A^(-1)*A?
A_invA = np.dot(A_inv, A)
print("A_invA: \n", A_invA)

Matrix A: 
 [[1 2 0]
 [0 5 6]
 [7 0 9]]
Matrix A_trans: 
 [[1 0 7]
 [2 5 0]
 [0 6 9]]
A_inv: 
 [[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]
A_invA: 
 [[ 1.00000000e+00 -8.32667268e-17  5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00 -8.32667268e-17]
 [-3.46944695e-17  2.77555756e-17  1.00000000e+00]]


***References***

  [1]. [Machine Learning by Andrew NG.](https://www.coursera.org/learn/machine-learning/home/welcome)